-- 修复 Supabase 表结构，使其与本地 SQLite 表结构匹配

-- 1. 修复 lab_push_candidates_v2 表
ALTER TABLE lab_push_candidates_v2 
ADD COLUMN IF NOT EXISTS issue VARCHAR,
ADD COLUMN IF NOT EXISTS sum_value INTEGER,
ADD COLUMN IF NOT EXISTS big_small VARCHAR,
ADD COLUMN IF NOT EXISTS odd_even VARCHAR,
ADD COLUMN IF NOT EXISTS dragon_tiger VARCHAR,
ADD COLUMN IF NOT EXISTS prediction_score DECIMAL,
ADD COLUMN IF NOT EXISTS confidence_level DECIMAL,
ADD COLUMN IF NOT EXISTS algorithm_version VARCHAR,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. 修复 cloud_pred_today_norm 表
ALTER TABLE cloud_pred_today_norm 
ADD COLUMN IF NOT EXISTS issue VARCHAR,
ADD COLUMN IF NOT EXISTS predicted_numbers VARCHAR,
ADD COLUMN IF NOT EXISTS prediction_type VARCHAR,
ADD COLUMN IF NOT EXISTS confidence_score DECIMAL,
ADD COLUMN IF NOT EXISTS normalization_factor DECIMAL,
ADD COLUMN IF NOT EXISTS model_version VARCHAR,
ADD COLUMN IF NOT EXISTS prediction_timestamp TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. 修复 signal_pool_union_v3 表
ALTER TABLE signal_pool_union_v3 
ADD COLUMN IF NOT EXISTS signal_type VARCHAR,
ADD COLUMN IF NOT EXISTS signal_strength DECIMAL,
ADD COLUMN IF NOT EXISTS pattern_match VARCHAR,
ADD COLUMN IF NOT EXISTS frequency_score DECIMAL,
ADD COLUMN IF NOT EXISTS reliability_index DECIMAL,
ADD COLUMN IF NOT EXISTS source_algorithm VARCHAR,
ADD COLUMN IF NOT EXISTS last_seen TIMESTAMP WITH TIME ZONE;

-- 4. 修复 p_size_clean_merged_dedup_v 表
ALTER TABLE p_size_clean_merged_dedup_v 
ADD COLUMN IF NOT EXISTS category_name VARCHAR,
ADD COLUMN IF NOT EXISTS size_range VARCHAR,
ADD COLUMN IF NOT EXISTS frequency_count INTEGER,
ADD COLUMN IF NOT EXISTS probability_score DECIMAL,
ADD COLUMN IF NOT EXISTS trend_indicator VARCHAR,
ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 5. 修复 draws_14w_dedup_v 表
ALTER TABLE draws_14w_dedup_v 
ADD COLUMN IF NOT EXISTS issue VARCHAR,
ADD COLUMN IF NOT EXISTS numbers VARCHAR,
ADD COLUMN IF NOT EXISTS sum_value INTEGER,
ADD COLUMN IF NOT EXISTS big_small VARCHAR,
ADD COLUMN IF NOT EXISTS odd_even VARCHAR,
ADD COLUMN IF NOT EXISTS dragon_tiger VARCHAR,
ADD COLUMN IF NOT EXISTS week_number INTEGER,
ADD COLUMN IF NOT EXISTS day_of_week INTEGER,
ADD COLUMN IF NOT EXISTS is_duplicate INTEGER,
ADD COLUMN IF NOT EXISTS dedup_hash VARCHAR,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 6. 修复 score_ledger 表
ALTER TABLE score_ledger 
ADD COLUMN IF NOT EXISTS issue VARCHAR,
ADD COLUMN IF NOT EXISTS actual_numbers VARCHAR,
ADD COLUMN IF NOT EXISTS predicted_numbers VARCHAR,
ADD COLUMN IF NOT EXISTS accuracy_score DECIMAL,
ADD COLUMN IF NOT EXISTS prediction_method VARCHAR,
ADD COLUMN IF NOT EXISTS evaluation_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS performance_metrics JSONB,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();